version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: php:8.1.0-fpm
    container_name: hillel_hw_16_php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./Docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - hillel_hw_16

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: hillel_hw_16_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "7777:80"
    volumes:
      - ./:/var/www
      - ./Docker/nginx/:/etc/nginx/conf.d/
    networks:
      - hillel_hw_16

  #MySQL Service
  db:
    image: mysql:5.7.24
    container_name: hillel_hw_16_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "7776:3306"
    environment:
      MYSQL_DATABASE: hillel_hw_16_db
      MYSQL_USER: hillel_hw_16_db
      MYSQL_PASSWORD: hillel_hw_16_db
      MYSQL_ROOT_PASSWORD: hillel_hw_16_db
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./Docker/mysql/data:/var/lib/mysql/
      - ./Docker/mysql/my.cnf:/etc/mysql/my.cnf
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - hillel_hw_16

  adminer:
    image: adminer
    container_name: hillel_hw_16_adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - hillel_hw_16

networks:
  hillel_hw_16:
    driver: bridge
